export function PrivacyPolicyContent() {
  return (
    <div className="text-sm sm:text-base space-y-5 text-slate-600 leading-relaxed">
      <p className="text-xs text-slate-400">Last updated: April 28, 2026</p>

      <p>ListedPEI ("we", "us", "our") is operated by PEI Web Studio and serves small businesses in Prince Edward Island, Canada. This policy explains what data we collect, why, and how we protect it.</p>

      <p className="font-bold text-slate-900 pt-2">1. Information You Provide</p>
      <p>When you use our Google Profile Kit generator, you enter business information such as your business name, category, address, phone number, website, and a description of your services. This information is transmitted directly to Google's Gemini AI to generate your profile kit and is <strong>never stored on our servers</strong>. If you submit your email address to receive your kit or book a consultation, that contact information is sent to us via EmailJS and stored locally in your browser.</p>

      <p className="font-bold text-slate-900 pt-2">2. Browser Storage</p>
      <p>We use your browser's <strong>localStorage</strong> to remember lead submissions and a visitor count badge (retained for up to 7 days). We use <strong>sessionStorage</strong> only for temporary admin authentication within a single browser session. No data is ever written to a third-party database by us.</p>

      <p className="font-bold text-slate-900 pt-2">3. Cookies</p>
      <p>We do not use tracking, advertising, or analytics cookies. The only browser storage we write is described in Section 2 above.</p>

      <p className="font-bold text-slate-900 pt-2">4. Third-Party Services</p>
      <ul className="list-disc pl-5 space-y-1">
        <li><strong>Google Gemini AI</strong> — your business inputs are processed by Google's API to generate content. See <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary-600 underline">Google's Privacy Policy</a>.</li>
        <li><strong>EmailJS</strong> — used to deliver your kit and lead notifications by email. See <a href="https://www.emailjs.com/legal/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-primary-600 underline">EmailJS's Privacy Policy</a>.</li>
      </ul>

      <p className="font-bold text-slate-900 pt-2">5. Data Retention</p>
      <p>We do not operate a backend database. Any lead data collected exists only in your local browser storage and in the email inbox of PEI Web Studio. You can clear your browser data at any time to remove locally stored information.</p>

      <p className="font-bold text-slate-900 pt-2">6. Your Rights</p>
      <p>You may request deletion of any email correspondence we hold by contacting us at <a href="mailto:peiwebstudio@gmail.com" className="text-primary-600 underline">peiwebstudio@gmail.com</a>. We will respond within 5 business days.</p>

      <p className="font-bold text-slate-900 pt-2">7. Children</p>
      <p>ListedPEI is intended for business owners and is not directed at anyone under the age of 16.</p>

      <p className="font-bold text-slate-900 pt-2">8. Changes to This Policy</p>
      <p>We may update this policy from time to time. The "Last updated" date at the top will reflect any changes. Continued use of the service after an update constitutes acceptance of the revised policy.</p>

      <p className="font-bold text-slate-900 pt-2">9. Contact</p>
      <p>Questions? Reach us at <a href="mailto:peiwebstudio@gmail.com" className="text-primary-600 underline">peiwebstudio@gmail.com</a> or visit <a href="https://peiwebstudio.ca" target="_blank" rel="noopener noreferrer" className="text-primary-600 underline">peiwebstudio.ca</a>.</p>
    </div>
  );
}

export function TermsOfServiceContent() {
  return (
    <div className="text-sm sm:text-base space-y-5 text-slate-600 leading-relaxed">
      <p className="text-xs text-slate-400">Last updated: April 28, 2026</p>

      <p>These Terms of Service govern your use of ListedPEI and any related services operated by PEI Web Studio. By accessing or using the service you agree to be bound by these terms.</p>

      <p className="font-bold text-slate-900 pt-2">1. The Service</p>
      <p>ListedPEI is a free AI-powered tool that generates Google Business Profile content for small businesses in Prince Edward Island. The service includes a profile kit generator, grant eligibility quiz, and promotional content for PickUp AI.</p>

      <p className="font-bold text-slate-900 pt-2">2. AI-Generated Content</p>
      <p>All profile content is generated by Google's Gemini AI model. While we tune our prompts for local SEO accuracy, we make no guarantee that the output is factually correct, complete, or suitable for your specific business. <strong>You are responsible for reviewing, editing, and verifying all generated content before publishing it</strong> to your Google Business Profile or any other platform.</p>

      <p className="font-bold text-slate-900 pt-2">3. No Guarantee of Results</p>
      <p>We do not guarantee any improvement in search rankings, visibility, or revenue as a result of using content generated by ListedPEI. SEO outcomes depend on many factors outside our control.</p>

      <p className="font-bold text-slate-900 pt-2">4. Acceptable Use</p>
      <p>You agree not to use ListedPEI to generate content that is false, misleading, defamatory, or in violation of any applicable law. You must be the owner or authorized representative of the business whose information you submit.</p>

      <p className="font-bold text-slate-900 pt-2">5. Intellectual Property</p>
      <p>The generated profile content is yours to use freely. The ListedPEI name, logo, design, and underlying code remain the property of PEI Web Studio.</p>

      <p className="font-bold text-slate-900 pt-2">6. Disclaimer of Warranties</p>
      <p>The service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or free of harmful components.</p>

      <p className="font-bold text-slate-900 pt-2">7. Limitation of Liability</p>
      <p>To the maximum extent permitted by law, PEI Web Studio shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.</p>

      <p className="font-bold text-slate-900 pt-2">8. Governing Law</p>
      <p>These terms are governed by the laws of the Province of Prince Edward Island and the federal laws of Canada applicable therein.</p>

      <p className="font-bold text-slate-900 pt-2">9. Changes to These Terms</p>
      <p>We reserve the right to update these terms at any time. The "Last updated" date will be revised accordingly. Continued use of the service constitutes acceptance of any changes.</p>

      <p className="font-bold text-slate-900 pt-2">10. Contact</p>
      <p>Questions about these terms? Email us at <a href="mailto:peiwebstudio@gmail.com" className="text-primary-600 underline">peiwebstudio@gmail.com</a>.</p>
    </div>
  );
}
